const QUESTIONS=[
{id:'C01Q011',block:'fetch',q:'¿Qué papel tiene fetch() en la primera conexión React Native → NestJS?',a:['Crear el Controller','Preparar y enviar la petición HTTP desde la app','Guardar permanentemente los datos','Volver a renderizar React por sí solo'],ok:1,ex:'fetch() es la pieza que utiliza la app para realizar la petición HTTP al backend. Después se procesa la respuesta recibida.',rein:'React Native → fetch() → HTTP → NestJS.'},
{id:'C01Q015',block:'useState',q:'¿Qué responsabilidad tiene setMensaje?',a:['Enviar un GET','Modificar el estado mensaje','Crear el valor inicial','Ejecutar @Controller'],ok:1,ex:'setMensaje es la función actualizadora. Al utilizarla cambiamos el estado y React puede volver a representar la interfaz con el nuevo valor.',rein:'setMensaje(nuevoValor) → cambia estado → nueva representación.'},
{id:'C01Q019',block:'useEffect / fetch',q:'¿Cuál refleja mejor el modelo mental del cuaderno?',a:['useEffect sustituye a fetch','fetch decide cuándo aparece la pantalla','useEffect decide cuándo llamar y fetch realiza la petición','useState realiza la petición y useEffect guarda el JSON'],ok:2,ex:'Son responsabilidades distintas: useEffect controla el momento de ejecución y cargarMensaje/fetch se encarga de comunicarse con la API.',rein:'Cuándo → useEffect. Comunicación → fetch.'},
{id:'C01Q021',block:'FlatList',q:'¿Para qué sirve renderItem en FlatList?',a:['Para indicar cómo se representa cada elemento del array','Para obtener el JSON del backend','Para crear IDs en NestJS','Para decidir el método HTTP'],ok:0,ex:'renderItem recibe cada item y define la interfaz que se construye para ese elemento de la colección.',rein:'data = qué elementos; renderItem = cómo se ve uno.'},
{id:'C01Q024',block:'PATCH',q:'¿Por qué el ejercicio de likes utiliza PATCH y no GET?',a:['Porque PATCH solicita modificar parcialmente un recurso y GET se utiliza para consultar','Porque GET no admite rutas','Porque PATCH es exclusivo de React Native','Porque PATCH guarda automáticamente en PostgreSQL'],ok:0,ex:'GET se usa para consultar información. El like modifica una parte del recurso existente, por eso el ejercicio introduce PATCH.',rein:'GET consulta; PATCH modifica parcialmente.'}
];
const $=s=>document.querySelector(s);let order=[],pos=0,seconds=30,timer=null,score=0,blank=0,locked=false,user={};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function home(){document.querySelector('#app').innerHTML=`<section class="card hero"><span class="tag">REPASO · NO ES UN EXAMEN</span><h1>Recupera lo aprendido bajo presión</h1><p>Tendrás <b>30 segundos</b> para decidir cada respuesta. Después el tiempo se detiene: verás una explicación y un modelo mental antes de continuar.</p><div class="grid"><div class="mini"><b>Una pregunta cada vez</b><span>Concéntrate en una decisión.</span></div><div class="mini"><b>Aprende después de responder</b><span>El feedback forma parte del ejercicio.</span></div></div><label>Nombre y apellidos</label><input id="name" class="input" autocomplete="name"><label>Correo</label><input id="email" class="input" type="email" autocomplete="email"><button class="primary wide" onclick="start()">COMENZAR REPASO</button></section>`}
function start(){const name=$('#name').value.trim(),email=$('#email').value.trim();if(!name||!email){alert('Introduce nombre y correo.');return}user={name,email};order=shuffle(QUESTIONS);pos=0;score=0;blank=0;show()}
function show(){clearInterval(timer);locked=false;seconds=30;const x=order[pos];const letters=['A','B','C','D'];$('#app').innerHTML=`<section class="card"><div class="quizhead"><div><span class="counter">PREGUNTA ${pos+1} DE ${order.length}</span><br><span class="block">${x.block}</span></div><div class="timer" id="timer">00:30</div></div><div class="track"><i id="timebar" style="width:100%"></i></div><h2 class="question">${x.q}</h2><div class="answers">${x.a.map((v,i)=>`<button class="answer" onclick="answer(${i})"><span class="letter">${letters[i]}</span><span>${v}</span></button>`).join('')}</div><div id="feedback"></div></section>`;timer=setInterval(tick,1000)}
function tick(){seconds--;const t=$('#timer');if(!t)return; t.textContent='00:'+String(seconds).padStart(2,'0');$('#timebar').style.width=(seconds/30*100)+'%';if(seconds<=10)t.classList.add('warn');if(seconds<=5)t.classList.add('danger');if(seconds<=0){clearInterval(timer);timeout()}}
function timeout(){if(locked)return;locked=true;blank++;reveal(null,true)}
function answer(i){if(locked)return;locked=true;clearInterval(timer);if(i===order[pos].ok)score++;reveal(i,false)}
function reveal(choice,isTimeout){const x=order[pos],buttons=[...document.querySelectorAll('.answer')];buttons.forEach((b,i)=>{b.disabled=true;if(i===x.ok)b.classList.add('correct');if(choice===i&&i!==x.ok)b.classList.add('wrong')});const good=choice===x.ok;$('#feedback').innerHTML=`<div class="feedback ${good?'ok':'bad'}"><h3>${isTimeout?'<span class="timeout">TIEMPO AGOTADO</span>':good?'✓ Correcto':'✕ Revisa este concepto'}</h3>${!good?`<p>La respuesta correcta es <b>${['A','B','C','D'][x.ok]} · ${x.a[x.ok]}</b>.</p>`:''}<div class="explain"><b>¿Qué debes aprender?</b><p>${x.ex}</p></div><div class="mental">${x.rein}</div><button class="primary wide" onclick="next()">${pos===order.length-1?'VER RESULTADO':'SIGUIENTE →'}</button></div>`}
function next(){pos++;if(pos>=order.length){finish()}else show()}
function finish(){clearInterval(timer);const n=order.length,note=(score/n*10).toFixed(1);$('#app').innerHTML=`<section class="card result"><span class="tag">REPASO COMPLETADO</span><h1>${user.name}</h1><p class="score">${note}</p><p>Resultado provisional de esta demostración. <b>Todavía no se envía a Google Sheets.</b></p><div class="summary"><div><b>${score}</b>Aciertos</div><div><b>${n-score-blank}</b>Errores</div><div><b>${blank}</b>Sin responder</div></div><button class="primary" onclick="home()">REPETIR DEMOSTRACIÓN</button></section>`}
home();