const $=s=>document.querySelector(s);let state={group:'',student:null,level:''};
const levels=[
 {id:'NC',title:'NO CONSEGUIDO',score:0,desc:'No he completado correctamente el Challenge 1.',flow:'Todavía no hay conexión básica completa.'},
 {id:'C1',title:'CHALLENGE 1 · CONEXIÓN BÁSICA',score:5,desc:'GET desde NestJS → React Native → estado → interfaz.',flow:'NestJS → GET → HTTP → React Native → estado → interfaz'},
 {id:'C2',title:'CHALLENGE 2 · PATH PARAM',score:7,desc:'Consulta por ID con Controller + Service + React Native.',flow:'ID → GET /alumnos/:id → @Param → Controller → Service → UI'},
 {id:'C3',title:'CHALLENGE 3 · LÓGICA EN SERVICE',score:10,desc:'Consulta de nivel con lógica situada en el Service.',flow:'GET /alumnos/:id/nivel → Controller → Service → lógica → UI'}
];
function render(){document.querySelector('#app').innerHTML=`<div class="shell"><header class="hero"><span class="eyebrow">${CHALLENGE_CONFIG.title}</span><h1>${CHALLENGE_CONFIG.date}</h1><p>CUADERNO FULL STACK · NestJS + React Native</p></header>
<section class="card"><h2>1 · Identifícate</h2><p class="muted">Selecciona tu grupo y después tu nombre. El correo institucional se asocia automáticamente.</p>
<label>GRUPO</label><select id="group" class="input"><option value="">Selecciona grupo…</option><option value="2SI">2ºSI</option><option value="2SID">2ºSID</option></select>
<label>ALUMNO</label><select id="student" class="input" disabled><option>Selecciona primero el grupo…</option></select><div id="email" class="email">Correo institucional: —</div></section>
<section class="card"><h2>2 · ¿Hasta dónde has llegado?</h2><p class="muted">Selecciona únicamente el nivel más alto que declaras haber completado correctamente.</p><div class="grid">${levels.map(l=>`<label class="level" data-level="${l.id}"><div><input type="radio" name="level" value="${l.id}"><strong>${l.title}</strong><span class="score">${l.score}/10</span></div><small>${l.desc}</small><div class="flow">${l.flow}</div></label>`).join('')}</div></section>
<section class="card"><h2>3 · Confirma tu declaración</h2><div class="summary"><div><b>ALUMNO</b><span id="sName">—</span></div><div><b>GRUPO</b><span id="sGroup">—</span></div><div><b>NIVEL DECLARADO</b><span id="sLevel">—</span></div><div><b>NOTA DECLARADA</b><span id="sScore">—</span></div></div><div class="notice">Esta es una <b>autoevaluación declarada</b>. No constituye automáticamente la calificación definitiva del profesor.</div><label class="check"><input id="confirm" type="checkbox"><span>Estoy declarando que he llegado correctamente hasta este nivel.</span></label><button id="send" class="primary" disabled>CONFIRMAR Y ENVIAR</button><div id="status"></div></section></div>`;bind()}
function bind(){const g=$('#group'),s=$('#student'),confirm=$('#confirm');g.onchange=()=>{state.group=g.value;state.student=null;s.innerHTML='<option value="">Selecciona alumno…</option>';(CHALLENGE_CONFIG.students[state.group]||[]).forEach((x,i)=>s.insertAdjacentHTML('beforeend',`<option value="${i}">${x[0]}</option>`));s.disabled=!state.group;update()};
s.onchange=()=>{const i=Number(s.value);state.student=Number.isInteger(i)&&s.value!==''?CHALLENGE_CONFIG.students[state.group][i]:null;update()};
document.querySelectorAll('input[name=level]').forEach(r=>r.onchange=()=>{state.level=r.value;document.querySelectorAll('.level').forEach(x=>x.classList.toggle('selected',x.dataset.level===state.level));update()});confirm.onchange=update;$('#send').onclick=submit;update()}
function update(){const l=levels.find(x=>x.id===state.level);$('#email').textContent='Correo institucional: '+(state.student?.[1]||'—');$('#sName').textContent=state.student?.[0]||'—';$('#sGroup').textContent=state.group||'—';$('#sLevel').textContent=l?.title||'—';$('#sScore').textContent=l?l.score+' / 10':'—';$('#send').disabled=!(state.group&&state.student&&state.student[1]&&state.level&&$('#confirm').checked)}
async function submit(){const btn=$('#send'),status=$('#status');btn.disabled=true;status.innerHTML='<p class="muted">Registrando declaración…</p>';const payload={action:'challenge',challengeId:'RN01-CHALLENGE-2026-10-01',grupo:state.group,alumno:state.student[0],email:state.student[1],nivel:state.level};
try{const r=await fetch(CHALLENGE_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const data=await r.json();if(!data.ok)throw new Error(data.error||'El servidor no confirmó el registro.');const l=levels.find(x=>x.id===state.level);document.querySelector('#app').innerHTML=`<div class="shell"><section class="card success"><div class="tick">✓</div><h1>CHALLENGE REGISTRADO</h1><p><b>${l.title}</b></p><h2>${l.score} / 10</h2><p>Nota declarada. No constituye automáticamente la calificación definitiva.</p><p class="muted">Se ha intentado enviar la confirmación al correo institucional: ${state.student[1]}</p></section></div>`}catch(e){status.innerHTML=`<p class="error">✕ No se ha podido registrar todavía. No cierres la página y vuelve a intentarlo.<br><small>${e.message}</small></p>`;btn.disabled=false}}
render();